CREATE TABLE IF NOT EXISTS "clients" (
	"id" serial PRIMARY KEY NOT NULL,
	"companyName" text NOT NULL,
	"cnpj" text NOT NULL,
	"cpf" text NOT NULL,
	"cep" text NOT NULL,
	"address" text NOT NULL,
	"locationNumber" text NOT NULL,
	"district" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"corfioCode" text NOT NULL,
	"phone" text NOT NULL,
	"email" text NOT NULL,
	"socialMedia" text NOT NULL,
	"contactAtCompany" text NOT NULL,
	"financialContact" text NOT NULL,
	"responsibleSeller" text NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"companySize" text NOT NULL,
	"hasOwnStore" text NOT NULL,
	"isJSMClient" text NOT NULL,
	"includedByJSM" text NOT NULL,
	"icmsContributor" text NOT NULL,
	"transportationType" text NOT NULL,
	"companyLocation" text NOT NULL,
	"marketSegmentNature" text NOT NULL
);
